### ISSUE TITLE
KeyError: 'rightUserId'

### ISSUE THREAD

**Issue by ChromoX** [mezz64/pyEight#6]
Hello,

I've had the following issue for about 2 months. I was hoping it would fix itself, but it hasn't. Any ideas?

Home Assistant(v0.90.2) Config:
```
eight_sleep:
    username: !secret eight_username
    password: !secret eight_password
    partner: false
```

Error:
```
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 151, in _async_setup_component
    hass, processed_config)
  File "/usr/src/app/homeassistant/components/eight_sleep/__init__.py", line 103, in async_setup
    success = await eight.start()
  File "/usr/local/lib/python3.7/site-packages/pyeight/eight.py", line 102, in start
    await self.assign_users()
  File "/usr/local/lib/python3.7/site-packages/pyeight/eight.py", line 149, in assign_users
    if data['result']['rightUserId'] == self._userid:
KeyError: 'rightUserId'
```

Thanks!

**Comment by mezz64** [comment]
Can you let me know if you're a single sleeper or if you have a partner and what side of the bed you sleep on?  Looks like they might have changed up the API a bit depending on how things are configured.

**Comment by ChromoX** [comment]
I am a single sleeper. On the left side of the bed from the viewpoint of the foot of the bed. Another way to say it is the side of the sensor on my model.
